/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../src/services/yahooTokenExchange`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/appGroup/frankings`; params?: Router.UnknownInputParams; } | { pathname: `/appGroup/makepicks`; params?: Router.UnknownInputParams; } | { pathname: `/appGroup/myPicks`; params?: Router.UnknownInputParams; } | { pathname: `/appGroup/stats`; params?: Router.UnknownInputParams; } | { pathname: `/appGroup/home/changePassword`; params?: Router.UnknownInputParams; } | { pathname: `/appGroup/home`; params?: Router.UnknownInputParams; } | { pathname: `/appGroup/home/makepicks`; params?: Router.UnknownInputParams; } | { pathname: `/appGroup/home/profile`; params?: Router.UnknownInputParams; } | { pathname: `/appGroup/home/settings`; params?: Router.UnknownInputParams; } | { pathname: `/authGroup/callback`; params?: Router.UnknownInputParams; } | { pathname: `/authGroup/login`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/services/yahooTokenExchange`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/appGroup/frankings`; params?: Router.UnknownOutputParams; } | { pathname: `/appGroup/makepicks`; params?: Router.UnknownOutputParams; } | { pathname: `/appGroup/myPicks`; params?: Router.UnknownOutputParams; } | { pathname: `/appGroup/stats`; params?: Router.UnknownOutputParams; } | { pathname: `/appGroup/home/changePassword`; params?: Router.UnknownOutputParams; } | { pathname: `/appGroup/home`; params?: Router.UnknownOutputParams; } | { pathname: `/appGroup/home/makepicks`; params?: Router.UnknownOutputParams; } | { pathname: `/appGroup/home/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/appGroup/home/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/authGroup/callback`; params?: Router.UnknownOutputParams; } | { pathname: `/authGroup/login`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/../src/services/yahooTokenExchange${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/appGroup/frankings${`?${string}` | `#${string}` | ''}` | `/appGroup/makepicks${`?${string}` | `#${string}` | ''}` | `/appGroup/myPicks${`?${string}` | `#${string}` | ''}` | `/appGroup/stats${`?${string}` | `#${string}` | ''}` | `/appGroup/home/changePassword${`?${string}` | `#${string}` | ''}` | `/appGroup/home${`?${string}` | `#${string}` | ''}` | `/appGroup/home/makepicks${`?${string}` | `#${string}` | ''}` | `/appGroup/home/profile${`?${string}` | `#${string}` | ''}` | `/appGroup/home/settings${`?${string}` | `#${string}` | ''}` | `/authGroup/callback${`?${string}` | `#${string}` | ''}` | `/authGroup/login${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../src/services/yahooTokenExchange`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/appGroup/frankings`; params?: Router.UnknownInputParams; } | { pathname: `/appGroup/makepicks`; params?: Router.UnknownInputParams; } | { pathname: `/appGroup/myPicks`; params?: Router.UnknownInputParams; } | { pathname: `/appGroup/stats`; params?: Router.UnknownInputParams; } | { pathname: `/appGroup/home/changePassword`; params?: Router.UnknownInputParams; } | { pathname: `/appGroup/home`; params?: Router.UnknownInputParams; } | { pathname: `/appGroup/home/makepicks`; params?: Router.UnknownInputParams; } | { pathname: `/appGroup/home/profile`; params?: Router.UnknownInputParams; } | { pathname: `/appGroup/home/settings`; params?: Router.UnknownInputParams; } | { pathname: `/authGroup/callback`; params?: Router.UnknownInputParams; } | { pathname: `/authGroup/login`; params?: Router.UnknownInputParams; };
    }
  }
}
